#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

HOST="${1:-}"
PROFILE="${2:-default}"
PORT="${3:-8000}"

if [ -z "$HOST" ]; then
  echo "Usage: ./setup.sh <ssh-host> [profile] [port]"
  echo "Example: ./setup.sh root@10.0.0.8 b200-lab 8000"
  exit 1
fi

OUT="$SCRIPT_DIR/$PROFILE.env"
if [ -f "$OUT" ]; then
  echo "ERROR: profile already exists: $OUT"
  echo "Edit it manually or remove it first."
  exit 1
fi

HOST_NO_USER="$HOST"
if [[ "$HOST" == *"@"* ]]; then
  HOST_NO_USER="${HOST##*@}"
fi

cat > "$OUT" <<EOF
# ============================================================
# devteam built-in bare-metal profile: $PROFILE
# Generated by setup.sh
# ============================================================

RAPID_HOST=$HOST
RAPID_CODE_DIR=/opt/dynamo
RAPID_SYNC_PATHS=""
RAPID_SERVICE_URL=$HOST_NO_USER:$PORT
RAPID_DEFAULT_CONFIG=default

RAPID_START_CMD="echo 'TODO: set RAPID_START_CMD (use {config})' && exit 1"
RAPID_STOP_CMD="pkill -f \"dynamo|vllm|pegaflow-server\" 2>/dev/null || true"
RAPID_STATUS_CMD="pgrep -fla \"dynamo|vllm|pegaflow-server\" || true"
EOF

echo "Profile written: $OUT"
echo "Next: edit RAPID_SYNC_PATHS and RAPID_START_CMD in this profile."
